apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
<<<<<<< HEAD
          image: module5-backend:latest
=======
          image: mbajwa2/module6-backend:c36879f19bac412afa97beab46af6206a7832078
>>>>>>> 8efae7a69b6ac8deb807815ae88f8994c9e43df3
          imagePullPolicy: Always
          ports:
            - containerPort: 5090
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/bank_app