apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
<<<<<<< HEAD
          image: mbajwa2/module6-backend:e52719e76a96a86f1eae775d0f134ded0d835b0b
=======
          image: mbajwa2/module6-backend:e52719e76a96a86f1eae775d0f134ded0d835b0b
>>>>>>> 8efae7a69b6ac8deb807815ae88f8994c9e43df3
          imagePullPolicy: Always
          ports:
            - containerPort: 5090
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/bank_app